irc:
  server:
    address: irc.example.com
    port: 7000
    ssl: Yes
    username: foo
    password: bar
  nickname: Examplebot
  nickservPassword: baz
  channels:
    - {name: '#example', key: }
    - {name: '#example-test', key: 'botsonly'}
  operator: Blort # nick of person who can issue restricted commands
modules:
  - {module: debug, class: DebugHandler, args: }
  - {module: story, class: Storybot, args:}
  - {module: help, class: HelpHandler, args: 'help.yaml'}
messages:
  register: You need to register!
