irc:
  server:
    address: irc.example.com
    port: 7000
    ssl: Yes
    username: foo
    password: bar
  nickname: Examplebot
  channels:
    - { name: '#example', key: }
    - { name: '#example-test', key: 'password' }
  operator: Blort # nick of person who can issue restricted commands
modules:
  - { module: debug, class: DebugHandler, args: }
  - { module: story, class: Storybot,     args: { yaml: storybot.yaml } }
  - { module: help,  class: HelpHandler,  args: { yaml: help.yaml } }
