irc:
  server:
    address: irc.example.com
    port: 7000
    ssl: Yes
    username: foo
    password: bar
  nickname: Examplebot
  channels:
    - { name: '#example', key: }
    - { name: '#example-test', key: 'password', ChanservInvite: Yes }
  operator: Blort # nick of person who can issue restricted commands
modules:
  - { module: debug, class: DebugHandler, args: }
  - { module: join, class: Join, args: }
  - module: mentor
    class: Mentor
    args:
      reportChannel: '#example'
  - { module: help,  class: HelpHandler,  args: { yaml: 'mentor/help.yaml' } }
